version: '3.7'

services:
  codetriangle:
    image: codetriangle:latest
    container_name: codetriangle
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ../codetriangle/main:/var/www/main
      - ../codetriangle/demo:/var/www/demo

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    ports:
      - 127.0.0.1:5004:2368
    volumes:
    - ../ghost:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      url: https://blog.codetri.net
