version: '3.6'

services:
  areyouonadate:
    image: areyouona-date:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000

  codetriangle:
    image: codetriangle:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5002:80
    volumes:
    - /usr/codetri/codetriangle:/var/www/html
