version: '3.6'

services:
  areyouonadate:
    image: areyouona-date:latest
    ports:
      - 127.0.0.1:5000:5000

  vss365today-web:
    image: vss365today-web:latest
    ports:
      - 127.0.0.1:5001:5000
    volumes:
      - /usr/codetri/vss-365-today/db:/app/db
