version: '3.7'

services:
  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   volumes:
  #     - /var/log/nginx:/var/log/nginx
  #     - /usr/codetri/codetri-server/sites-available:/etc/nginx/sites-available
  #     - /usr/codetri/codetri-server/conf.d:/etc/nginx/conf.d
  #   ports:
  #     - 127.0.0.1:80:80

  codetriangle:
    image: codetriangle:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
    - /usr/codetri/codetriangle:/var/www/html

  areyouonadate:
    image: areyouona-date:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5001:5000

  vss365today:
    image: vss365today:latest
    restart: unless-stopped
    volumes:
      - /usr/codetri/vss365-today:/app
    ports:
      - 127.0.0.1:5002:5000
    entrypoint:
      - sh
      - ./run-flask.sh

  ghost:
    image: ghost:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5003:2368
    volumes:
    - /usr/codetri/ghost:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      url: http://blog.codetri.net