version: '3.8'

services:
  codetriangle:
    image: codetriangle:latest
    container_name: codetriangle
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ../codetriangle/demo:/var/www/demo

  ghost:
    image: ghost:4
    container_name: ghost
    restart: unless-stopped
    ports:
      - 127.0.0.1:5004:2368
    volumes:
    - ../ghost:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      url: http://blog.codetri.net
    networks:
      - codetri
      
  # database:
  #   image: mysql:8.0
  #   container_name: database
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #    volumes:
  #     - ../api/db:/docker-entrypoint-initdb.d
  #     - ../db:/var/lib/mysql
  #     - ../secrets:/app/secrets
  #   ports:
  #     - 127.0.0.1:3306:3306
  #   environment:
  #     - MYSQL_DATABASE=vss365today
  #     - MYSQL_USER_FILE=/app/secrets/DB_USERNAME
  #     - MYSQL_PASSWORD_FILE=/app/secrets/DB_PASSWORD
  #     - MYSQL_ROOT_PASSWORD_FILE=/app/secrets/DB_PASSWORD_ROOT
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   networks:
  #     - codetri
