version: '3.7'

services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ../nginx/log:/var/log/nginx
  #     - ../sites-available:/etc/nginx/sites-available
  #     - ../conf.d:/etc/nginx/conf.d

  codetriangle:
    image: codetriangle:latest
    container_name: codetriangle
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ../codetriangle:/var/www/html

  areyouonadate:
    image: areyouona-date:latest
    container_name: areyouonadate
    restart: unless-stopped
    ports:
      - 127.0.0.1:5001:5000

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    ports:
      - 127.0.0.1:5004:2368
    volumes:
    - ../ghost:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      url: http://blog.codetri.net
