version: '3.8'

services:
  codetriangle:
    image: codetriangle:latest
    container_name: codetriangle
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ../codetriangle/demo:/var/www/demo

  # ghost:
  #   image: ghost:4
  #   container_name: ghost
  #   restart: unless-stopped
  #   ports:
  #     - 127.0.0.1:5004:2368
  #   volumes:
  #   - ../ghost:/var/lib/ghost/content
  #   environment:
  #     NODE_ENV: production
  #     url: http://blog.codetri.net
  #   networks:
  #     - codetri

  ghost5:
    image: ghost:5
    container_name: ghost5
    restart: unless-stopped
    ports:
      - 127.0.0.1:5005:2368
    volumes:
    - ../ghost5:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      url: https://blog2.codetri.net
      database__client: mysql
      database__connection__host: database
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
    networks:
      - codetri
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
      - 127.0.0.1:33060:33060
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=ghost
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - codetri

networks:
  codetri:
    driver: bridge
