version: '3.7'

services:
  vss365today:
    image: vss365today:latest
    container_name: vss365today
    restart: unless-stopped
    volumes:
      - ../vss365-today:/app
      - ../vss365-today/log:/var/log
      - ../vss365-today-api/db:/app/db
    ports:
      - 127.0.0.1:5002:5000
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  vss365today-api:
    image: vss365today-api:latest
    container_name: vss365today-api
    restart: unless-stopped
    volumes:
      - ../vss365-today-api:/app
      - ../vss365-today-api/log:/var/log
    ports:
      - 127.0.0.1:5003:5000
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  postfix:
    image: boky/postfix
    container_name: mail.codetri.net
    ports:
      - 127.0.0.1:1587:587
    volumes:
      - ../email/keys:/etc/opendkim/keys
      - ../email/startup-scripts:/docker-init.db/
    environment:
      - HOSTNAME=mail.codetri.net
      - ALLOWED_SENDER_DOMAINS=codetri.net
    networks:
      - vss365today

networks:
  vss365today:
    driver: bridge
