version: '3.7'

services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   volumes:
  #     - /var/log/nginx:/var/log/nginx
  #     - ../sites-available:/etc/nginx/sites-available
  #     - ../conf.d:/etc/nginx/conf.d
  #   ports:
  #     - 80:80

  codetriangle:
    image: codetriangle:latest
    container_name: codetriangle
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
    - ../codetriangle:/var/www/html

  areyouonadate:
    image: areyouona-date:latest
    container_name: areyouonadate
    restart: unless-stopped
    ports:
      - 127.0.0.1:5001:5000

  vss365today:
    image: vss365today:latest
    container_name: vss365today
    restart: unless-stopped
    volumes:
      - ../vss365-today:/app
    ports:
      - 127.0.0.1:5002:5000
    entrypoint:
      - sh
      - ./run-flask.sh
    networks:
      - codetriangle

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    ports:
      - 127.0.0.1:5003:2368
    volumes:
    - ../ghost:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      url: http://blog.codetri.net

  postfix:
    image: boky/postfix
    container_name: mail.codetri.net
    ports:
      - 127.0.0.1:1587:587
    volumes:
      - ../email/keys:/etc/opendkim/keys
      - ../email/startup-scripts:/docker-init.db/
    environment:
      - HOSTNAME=mail.codetri.net
      - ALLOWED_SENDER_DOMAINS=vss365today.com
    networks:
      - codetriangle

networks:
  codetriangle:
    driver: bridge
