version: '3.7'

services:
  vss365today-web:
    image: vss365today-web:latest
    container_name: vss365today-web
    restart: unless-stopped
    volumes:
      - ../../vss365today/web:/app
      - ../../vss365today/web/log:/var/log
      - ../../vss365today/secrets:/app/secrets
      - /var/www/vss365today/images:/app/src/static/prompt-images
      - /var/www/vss365today/downloads:/app/src/static/downloads
    ports:
      - 127.0.0.1:5002:80
    environment:
      - FLASK_ENV=production
      - SYS_VARS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  vss365today-api:
    image: vss365today-api:latest
    container_name: vss365today-api
    restart: unless-stopped
    volumes:
      - ../../vss365today/api:/app
      - ../../vss365today/api/log:/var/log
      - ../../vss365today/secrets:/app/secrets
      - /var/www/vss365today/images:/app/images
      - /var/www/vss365today/downloads:/app/downloads
    ports:
      - 127.0.0.1:5003:80
    environment:
      - FLASK_ENV=production
      - SYS_VARS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  vss365today-finder:
    image: vss365today-finder:latest
    container_name: vss365today-finder
    restart: unless-stopped
    volumes:
      - ../../vss365today/finder:/app
      - ../../vss365today/secrets:/app/secrets
      - /var/www/vss365today/downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - SYS_VARS_PATH=/app/secrets
      - DOWNLOADS_PATH=/app/downloads
      - SCHEDULE_TIMES=["05 11", "25 11", "45 11", "05 12"]
    entrypoint:
      - python
      - ./finder.py
      - --schedule
    networks:
      - vss365today

  vss365today-db:
    image: mariadb:10.4
    container_name: vss365today-db
    restart: unless-stopped
    volumes:
      - ../../vss365today/api/db:/docker-entrypoint-initdb.d
      - ../../vss365today/secrets:/secrets
      - ../../vss365today/db/:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=vss365today
      - MYSQL_USER_FILE=/secrets/DB_USERNAME
      - MYSQL_PASSWORD_FILE=/secrets/DB_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/secrets/DB_PASSWORD_ROOT
    networks:
      - vss365today

  # Run a database backup at midnight every Sunday
  mysql-backup:
    image: databack/mysql-backup
    container_name: mysql-backup
    restart: unless-stopped
    volumes:
      - ../../vss365today/backup:/backup
    environment:
      - DB_DUMP_SAFECHARS=true
      - DB_DUMP_CRON=0 0 * * 0
      - DB_SERVER=vss365today-db
      - DB_PORT=3306
      - DB_NAMES=vss365today
      - DB_DUMP_TARGET=/backup
      - NICE=true
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
        - vss365today

networks:
  vss365today:
    driver: bridge
