version: '3.7'

services:
  vss365today-web:
    image: vss365today-web:latest
    container_name: vss365today-web
    restart: unless-stopped
    volumes:
      - ../../vss365today/web:/app
      - ../../vss365today/web/log:/var/log
      - ../../vss365today/secrets:/app/secrets
      - ../../vss365today/static/images:/app/src/static/prompt-images
      - ../../vss365today/static/downloads:/app/src/static/downloads
    ports:
      - 127.0.0.1:5002:80
    environment:
      - FLASK_ENV=production
      - DOCKER_SECRETS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  vss365today-api:
    image: vss365today-api:latest
    container_name: vss365today-api
    restart: unless-stopped
    volumes:
      - ../../vss365today/api:/app
      - ../../vss365today/api/log:/var/log
      - ../../vss365today/secrets:/app/secrets
      - ../../vss365today/static/images:/app/images
      - ../../vss365today/static/downloads:/app/downloads
    ports:
      - 127.0.0.1:5003:80
    environment:
      - FLASK_ENV=production
      - DOCKER_SECRETS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  vss365today-finder:
    image: vss365today-finder:latest
    container_name: vss365today-finder
    restart: unless-stopped
    volumes:
      - ../../vss365today/finder:/app
      - ../../vss365today/secrets:/app/secrets
      - ../../vss365today/static/downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - DOCKER_SECRETS_PATH=/app/secrets
      - DOWNLOADS_PATH=/app/downloads
      - SCHEDULE_TIMES=["25 4", "45 4", "05 5", "25 5"]
    entrypoint:
      - python
      - ./finder.py
      - --schedule
    networks:
      - vss365today

  vss365today-db:
    image: mariadb:10.4
    container_name: vss365today-db
    restart: unless-stopped
    volumes:
      - ../../vss365today/api/db:/docker-entrypoint-initdb.d
      - ../../vss365today/secrets:/secrets
      - ../../vss365today/db/:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=vss365today
      - MYSQL_USER_FILE=/secrets/DB_USERNAME
      - MYSQL_PASSWORD_FILE=/secrets/DB_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/secrets/DB_PASSWORD_ROOT
    networks:
      - vss365today

networks:
  vss365today:
    driver: bridge
