version: '3.7'

services:
  vss365today:
    image: vss365today:latest
    container_name: vss365today
    restart: unless-stopped
    volumes:
      - ../../vss365-today:/app
      - ../../vss365-today/log:/var/log
      - /app/app/static/build/
    ports:
      - 127.0.0.1:5002:5000
    environment:
      - FLASK_ENV=production
      - DOCKER_SECRETS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  vss365today-api:
    image: vss365today-api:latest
    container_name: vss365today-api
    restart: unless-stopped
    volumes:
      - ../../vss365-today-api:/app
      - ../../vss365-today-api/log:/var/log
      - ../../vss365-today/src/static/prompt-images:/app/images
    ports:
      - 127.0.0.1:5003:5000
    environment:
      - FLASK_ENV=production
      - DOCKER_SECRETS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  mariadb:
    image: mariadb:10.4
    container_name: vss365today-db
    restart: unless-stopped
    volumes:
      - ../../vss365-today-api/db:/docker-entrypoint-initdb.d
      - ../../vss365-today-api/secrets:/secrets
      - ../../vss365-today-db/:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=vss365today
      - MYSQL_USER_FILE=/secrets/DB_USERNAME
      - MYSQL_PASSWORD_FILE=/secrets/DB_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/secrets/DB_PASSWORD_ROOT
    networks:
      - vss365today

networks:
  vss365today:
    driver: bridge
